---
title: "Assets"
date: today
---

Introduction
--------------------------------------------

TODO: What are the investments we can hold?


Asset classes
--------------------------------------------

-   stocks: individual stocks, ETFs, mutual funds
-   bonds: treasuries, corporate bonds, municipal bonds
-   real estate, REITs
-   commodities, metals
-   cryptocurrency
-   collectables


US sectors
--------------------------------------------

There are 11 sectors in the [standard classification by MSCI](https://en.wikipedia.org/wiki/Global_Industry_Classification_Standard), see @tbl-us-sectors.

Table: The 11 sectors in the [standard classification by MSCI](https://en.wikipedia.org/wiki/Global_Industry_Classification_Standard). Classification of super sectors by [Morningstar Stock Sector Structure](https://www.morningstar.com/content/dam/marketing/apac/au/pdfs/Legal/StockSectorStructure_Factsheet.pdf) (2011), where C=Cyclical, D=Defensive, S=Sensitive. Market cap data is from [this blog](https://www.visualcapitalist.com/largest-company-market-cap-sp-500-market-concentration/) (2024). {#tbl-us-sectors}

|  #  | Sector         | Super Sector | Market Cap [T$] | Market Cap [%] | Largest Co   | Co share [%] | Vanguard ETF |
|----:|:---------------|:-------------|----------------:|---------------:|:-------------| ------------:|:-------------|
|  1  | Technology     | S            |            15.3 |           31.7 | Microsoft    |         22.3 | VGT          |
|  2  | Financials     | C            |             6.1 |           12.7 | Berkshire    |         12.9 | VFH          |
|  3  | Healthcare     | D            |             5.6 |           11.6 | Eli Lilly    |         13.5 | VHT          |
|  4  | Discretionary  | C            |             4.9 |           10.2 | Amazon       |         38.8 | VCR          |
|  5  | Communications | S            |             4.6 |            9.5 | Alphabet     |         25.8 | VOX          |
|  6  | Industrials    | S            |             3.9 |            8.1 | GE Aerospace |          4.7 | VIS          |
|  7  | Staples        | D            |             3.0 |            6.2 | Walmart      |         14.7 | VDC          |
|  8  | Energy         | S            |             1.7 |            3.5 | Exxon Mobil  |         30.9 | VDE          |
|  9  | Real estate    | C            |             1.1 |            2.3 | Prologis     |         10.5 | VNQ          |
| 10  | Utilities      | D            |             1.0 |            2.1 | NextEra      |         14.0 | VPU          |
| 11  | Materials      | C            |             1.0 |            2.1 | Linde        |         21.4 | VAW          |


Stock market is not the economy
--------------------------------------------

-   Small businesses employ nearly half of the American workforce and represent 43.5% of America’s GDP.
-   Only [13% (2,790)](https://www.advisorpedia.com/chart-center/number-of-public-companies-v-private-us/) of US companies with over $100 million in revenue are publicly traded.
-   Private equity is becoming more influential.
-   Schlingemann, F.P. & Stulz, R.M. (2022). Have exchange-listed firms become less important for the economy? [^Schlingemann2022]

[^Schlingemann2022]: HERE


Global stock markets
--------------------------------------------

-   TODO


Active vs passive
--------------------------------------------

-   Brinson, G.P., Hood, L.R., & Beebower, G.L. (1986). Determinants of portfolio performance. [^Brinson1986]
-   Brinson, G. P., Singer, B.D., & Beebower, G.L. (1991). Determinants of portfolio performance II: An update. [^Brinson1991]
-   Hood, R.L. (2005). Determinants of portfolio performance: 20 years later. [^Hood2005]

[^Brinson1986]: @Brinson_1986_Determinants_of_portfolio_performance\.
[^Brinson1991]: @Brinson_1991_Determinants_of_portfolio_performance_II\.
[^Hood2005]: @Hood_2005_Determinants_of_portfolio_performance_20_years\.


