---
date: today
---

# Convex optimization {#sec-convex-optimization}


Introduction
--------------------------------------------

This is how we minimize $\sigma$.

-   [Linear programming](https://en.wikipedia.org/wiki/Linear_programming)
    -   [George Dantzig](https://en.wikipedia.org/wiki/George_Dantzig) (1914-2005)
-   [Quadratic programming](https://en.wikipedia.org/wiki/Quadratic_programming)
    -   No-shorts efficient frontier
    -   [Karush-Kuhn-Tucker (KKT) conditions](https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions)
    -   Jagannathan, R. & Ma, T. (2003). Risk reduction in large portfolios: Why imposing the wrong constraints helps. [^Jagannathan2003]
    -   Tam, A.S. (2021). [Lagrangians and portfolio optimization](https://www.adrian.idv.hk/2021-06-22-kkt/).
-   Boyd, S. & Vandenberghe, L. (2004). [*Convex Optimization*](https://web.stanford.edu/~boyd/cvxbook/). [^Boyd2004]
    -   Course website at Stanford: [Convex Optimization I](https://web.stanford.edu/class/ee364a/)
    -   [Convex Optimization Short Course](https://web.stanford.edu/~boyd/papers/cvx_short_course.html)
    -   Boyd Lectures on youtube: [1](https://www.youtube.com/watch?v=kV1ru-Inzl4), [2](https://www.youtube.com/watch?v=2H4_7izio9Y), [3](https://www.youtube.com/watch?v=1menqhfNzzo), [4](https://www.youtube.com/watch?v=U2HRwA7XePU), [5](https://www.youtube.com/watch?v=AAjG1TQcL7c), [6](https://www.youtube.com/watch?v=d2jF3SXcFQ8), [7](https://www.youtube.com/watch?v=P_SuSVZnrT0), [8](https://www.youtube.com/watch?v=wsRznzNgTS0), [9](https://www.youtube.com/watch?v=whE03c84ahA), [10](https://www.youtube.com/watch?v=N3V2AdTImJE), [11](https://www.youtube.com/watch?v=trs0RI39uWI), [12](https://www.youtube.com/watch?v=ankx1lGi5jI)
    -   Affine combinations and convex sets
-   Markowitz's  Critical Line Algorithm (CLA)
    -   Markowitz, H.M. (1956). The optimization of a quadratic function subject to linear constraints. [^Markowitz1956]
    -   Bailey, D.H. & L&oacute;pez de Prado, M. (2013). [An open-source implementation of the critical-line algorithm for portfolio optimization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2197616). [^Bailey2013]
    -   Markowitz, H.M., Starer, D., Fram, H., & Gerber, S. (2019). [Avoiding the downside: A practical review of the Critical Line Algorithm for mean-semivariance portfolio optimization](https://www.hudsonbaycapital.com/documents/FG/hudsonbay/research/599440_paper.pdf). [^Markowitz2019a]
-   Software:
    -   [CVXPY](https://www.cvxpy.org/)
    -   [robertmartin8/PyPortfolioOpt](https://github.com/robertmartin8/PyPortfolioOpt)
    -   [scikit-portfolio](https://scikit-portfolio.github.io/scikit-portfolio/)
    -   [mdengler/cla](https://github.com/mdengler/cla/)

TODO: Discuss optimizing the no-shorts frontier.

[^Bailey2013]: @Bailey_2013_An_open_source_implementation_of_the_critical_line\.
[^Boyd2004]: @Boyd_2004_Convex_Optimization\.
[^Jagannathan2003]: @Jagannathan_2003_Risk_reduction_in_large_portfolios_Why_imposing\.
[^Markowitz1956]: @Markowitz_1956_The_optimization_of_a_quadratic_function_subject\.
[^Markowitz2019a]: @Markowitz_2019_Avoiding_the_downside_A_practical_review\.


