---
title: "Value investing"
date: today
---

Introduction
--------------------------------------------

TODO: Price data is pretty easy to come by, but where does one scrape
up-to-date earnings data?


Growth vs value investing
--------------------------------------------

-   TODO
-   Asness, C.S., Frazzini, A., & Pedersen, L.H. (2019). [Quality minus junk](https://doi.org/10.1007/s11142-018-9470-2). [^Asness2019]

[^Asness2019]: @Asness_2019_Quality_minus_junk\.


P/E ratio
--------------------------------------------

Tables of P/E by US industry:

-   [Aswath Damodaran (NYU)](https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/pedata.html)
-   [fullratio.com](https://fullratio.com/pe-ratio-by-industry)

P/E ratio by S&P500 sector:

-   [worldperatio.com](https://worldperatio.com/sp-500-sectors/)
-   [macromicro.me](https://en.macromicro.me/collections/5749/industry-forward-pe-ratio/48243/s5cond-forward-pe-ratio) - Forward P/E
-   [yardeni.com](https://yardeni.com/charts/sp-500-sectors-forward-p-e-ratios/) - Forward P/E over time

Discussion:

-   Estrada, J. (2005). [The Fed Model: A note](https://ssrn.com/abstract=841787). [^Estrada2005]
-   [Fed model](https://en.wikipedia.org/wiki/Fed_model)

[^Estrada2005]: @Estrada_2005_The_Fed_Model_A_note\.


Margin of safety
--------------------------------------------

-   [Margin of safety](https://en.wikipedia.org/wiki/Margin_of_safety_(financial))
-   [Benjamin Graham](https://en.wikipedia.org/wiki/Benjamin_Graham) (1894-1976)
    -   *The Intellegent Investor* (1949) [^Graham2003]

![The cost of loss [@Graham_2003_The_Intellegent_Investor_Revised_ed\, p. 526]\.](img/graham-cost-of-loss.png){#fig-graham-cost-of-loss}

[^Graham2003]: @Graham_2003_The_Intellegent_Investor_Revised_ed\.


Buffett Indicator
--------------------------------------------

-   [Buffett Indicator](https://www.currentmarketvaluation.com/models/buffett-indicator.php)
-   [Longtermtrends: Buffett Indicator](https://www.longtermtrends.net/market-cap-to-gdp-the-buffett-indicator/)
-   [Longtermtrends: S&P 500 P/E Ratio](https://www.longtermtrends.net/sp500-price-earnings-shiller-pe-ratio/)
-   [multpl.com: Shiller P/E](https://www.multpl.com/shiller-pe)
-   [Warren Buffett](https://en.wikipedia.org/wiki/Warren_Buffett) (b. 1930)
-   Buffett, W. (2017). *Berkshire Hathaway Letters to Shareholders 1965-2016*. [^Buffett2017]

[^Buffett2017]: @Buffett_2017_Berkshire_Hathaway_Letters_to_Shareholders\.


Reading a 10-K
--------------------------------------------

-   [How to read a 10-K/10-Q](https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/how-read)
-   Find a particular company's 10-K filings using the search for the SEC's [EDGAR database](https://www.sec.gov/search-filings). 


Graham's special paradox of mathematics and investment
--------------------------------------------

As a physicist, I support the skillful application of mathematics.
In these notes, we have used some calculus, linear algebra, and numerical
optimizations.

Still, noting Graham:

>   [T]here is a special paradox in the relationship between mathematics and
>   investment attitudes on common stocks, which is this: Mathematics is
>   ordinarily considered as producing precise and dependable results;
>   but in the stock market the more elaborate and abstruse the mathematics
>   the more uncertain and speculative are the conclusions we draw therefrom.
>   In 44 years of Wall Street experience and study I have never seen
>   dependable calculations made about common stock values, or related
>   investment policies, that went beyond simple arithmetic or the most
>   elementary algebra. Whenever calculus is brought in, or higher algebra,
>   you could take it as a warning signal that the operator was trying to
>   substitute theory for experience, and usually also to give to speculation
>   the deceptive guise of investment. [^Graham2003p570]

[^Graham2003p570]: @Graham_2003_The_Intellegent_Investor_Revised_ed\, p. 570.


Misc
--------------------------------------------

-   Alden, Lyn. (?). [How to invest in stocks](https://www.lynalden.com/how-to-invest-in-stocks/).
-   [The Measure of a Plan](https://themeasureofaplan.com/)
-   [Mr. Market by Benjamin Graham](http://csinvesting.org/wp-content/uploads/2013/10/Mr-Market-by-Ben-Graham.pdf) - Chapter 8 from *The Intelligent Investor* with commentary by Jason Zweig
-   Wikipedia:
    -   [Benjamin Graham formula](https://en.wikipedia.org/wiki/Benjamin_Graham_formula)
    -   [Discounted cash flow](https://en.wikipedia.org/wiki/Discounted_cash_flow)
    -   [Magic formula investing](https://en.wikipedia.org/wiki/Magic_formula_investing) - Joel Greenblatt
    -   [Market Rules to Remember](https://en.wikipedia.org/wiki/Market_Rules_to_Remember) - Bob Farrell (1998), Merrill Lynch
    -   [Triple witching hour](https://en.wikipedia.org/wiki/Triple_witching_hour)
    -   [Value investing](https://en.wikipedia.org/wiki/Value_investing)


